PropelPLM/pim-data-service

local/testLegacyExportProduct.js, package-lock.json
just updating the test file with Ids from QA
=> some small changes and testing

index.js, package-lock.json, package.json, test/TestRouts.js
Adding tests for the routes, more tests to come. But these tests will catch anything wrong with calling the routes. The issue with PIM-403 was module not defined because I didn't add the correct path for the a module that was called from a route.
=> creating tests for Routes

legacy/PimProductListHelper.js, legacy/PimProductManager.js, legacy/PimProductService.js, service/PimProductDeep.js
thanks Kim for reminding me to take care of Title__c in the data service.
=> removing title__c from export

local/testImportProduct.js, service/PimProduct.js
looks like namespace doesn't work on subqueries.
=> PIM-566 fixing the query to work with namespaces

legacy/PimStructure.js
Refactoring due to change in data model on the salesforce side, also name change to make it more intuitive
PIM repo PR: https://github.com/PropelPLM/PIM/pull/513/
=> PIM-454: PIM | Attribute <> Category relationship

legacy/PimStructure.js
Added validation for Attribute labels of type Digital Asset and convert the Digital_Asset__c id to their data page url
=> PIM-576: PIM | Export | Digital Asset Attributes are exporting as the ID instead of the URL

legacy/PimExportHelper.js, legacy/PimStructure.js, legacy/utils.js
Per the JIRA comments, instead of converting the SObject Id to the salesforce data page URL, the SObject Id is changed to the CDN URL
https://user-images.githubusercontent.com/77341283/207557248-841ee982-6181-4a8a-9322-df3d15242128.mov
=> PIM-576-2: PIM | Export | Digital Asset Attributes are exporting as the ID instead of the URL 

legacy/ExportPIM.js, legacy/PimProductListHelper.js, legacy/PimStructure.js
Call propel-document-java to send it the necessary information for it to handle xlsx templated exports
https://user-images.githubusercontent.com/77341283/213243932-a109e5d2-c635-48cf-bab8-ae43bc7aa6dc.mov
PR for PIM repo: https://github.com/PropelPLM/PIM/pull/582
PR for propel-document-java repo: https://github.com/PropelPLM/propel-document-java/pull/18
=> PIM-380: PIM | Export | Allow for templated export to be XLSX

legacy/ExportPIM.js, legacy/PimProductListHelper.js
- Added null check for null return values in the event that export is handled elsewhere
- Removed unnecessary `console.log` statements
=> PIM-380: Cleanup and Null Check

ChimeraToken.txt
Need to add this token so the security scanner tool, Chimera can scan our heroku data app for stuff.
=> adding the scanner token

legacy/ExportPIM.js, legacy/PimProductListHelper.js, legacy/PimStructure.js, legacy/utils.js
New functionalities added:
-  exporting to xlsx format
-  exporting xlsx templates to csv format
PR for PIM repo: https://github.com/PropelPLM/PIM/pull/595
PR for propel-document-java repo: https://github.com/PropelPLM/propel-document-java/pull/19
=> PIM-294: PIM | Export | New export format XLSX

legacy/PimStructure.js
- remove Category column
- rename Category__r.Name column to Category
=> PIM-655: PIM | Export | Clean up Category data headers

legacy/ExportPIM.js, legacy/PimProductListHelper.js, legacy/PimProductService.js, legacy/PimRecordListHelper.js, legacy/PimRecordManager.js, legacy/PimRecordService.js, legacy/PimStructure.js, legacy/utils.js, package-lock.json, package.json, test/PimStructure.test.js, test/utils.test.js
Seeing how the current code is so unmaintainable, I feel it is important that we get this refactor in before we can do other tasks.
If you have an extra half an hour in between meetings/tasks, or if you want a logical break (or to even just do a good deed for today), you can help contribute to the refactoring effort! I'm personally going to start by breaking down the super huge method into manageable chunks each day.
That said, the refactoring goals are:
- Maintainability - If I get hit by a bus tomorrow, can literally any other dev take over my work the next day with minimal onboarding effort?
- key markers include but are not limited to: 
1.    Is my function doing one thing and one thing only?
2.    Am I repeating code that is somewhere else in the codebase?
3.    Is my code readable? …
=> [DO NOT MERGE] PIM-254: Refactor Export Heroku App

legacy/PimStructure.js, legacy/utils.js
- Added in bug fixes from recent PR that were overwritten during refactoring
- Defined some missing variables
=> PIM-714: PIM | Export | Export failing in PDP for products without variant values and when filling in inherited data

legacy/ExportPIM.js, legacy/PimRecordListHelper.js, legacy/PimRecordManager.js, legacy/PimRecordService.js, legacy/PimStructure.js, legacy/utils.js, lib/ExportProduct.js, test/PimStructure.test.js
Consolidated certain shared methods like the aspose calls so that both DAs and Products can use the same general flow for export.
=> PIM-441: Digital Asset List page | Metadata Export 

legacy/utils.js
add mimetype to payload for DA download to be able to append extension if not present
=> PIm-773: When file name is edited the export does not include an extension

legacy/ExportPIM.js
Supporting PR for https://github.com/PropelPLM/PIM/pull/739
=> PIM-788: Add export options for DA records

legacy/utils.js
Fixed bug where PLP SKU export would only return variant values with most number of parent variant values out of all variant values in export selection (should be most parent variant values out of all variant values per product)
This is done by maintaining 2 `Map()` data structures which track each product's highest parent variant value count and another that tracks each product's list of variant values with that highest parent variant value count
=> PIM-476-3: PIM | Add ability to only download lowest level Variant on Product List page and Product Data page

legacy/PimRecordListHelper.js, legacy/utils.js
Additional enhancement as per Chris' comment:
=> PIM-422-1: Digital Asset List page | Binary Export > Title column should be removed

legacy/utils.js
Forgot that first level variants can be SKUs
=> PIM-476: PIM | Add ability to only download lowest level Variant on Product List page and Product Data page

legacy/utils.js
https://user-images.githubusercontent.com/77341283/227159615-8e6cda97-f2a6-45ba-bd47-4e8059d5f830.mov
tested and working in QA ^
=> PIM-476-5: PIM | Add ability to only download lowest level Variant on Product List page and Product Data page

legacy/PimRecordListHelper.js, legacy/PimStructure.js, legacy/utils.js
=> PIM-811: PIM | Export | Attribute Values of Type ProductReference are Displaying as SObject ID instead of Product ID

legacy/PimStructure.js
=> PIM-681: PIM | Export | Enhancements to Modal and functionality

index.js, lib/ImportAttributeTab.js, lib/ImportCategory.js, lib/ImportProduct.js, lib/utility.js, package-lock.json, package.json
Check https://github.com/PropelPLM/PIM/pull/905
=> PIM-595: PIM | Import | Allow data imports to handle XLSX filetype

index.js, legacy/ExportPIM.js, lib/AttributeGroup.js, lib/ImportAttributeGroup.js, lib/ImportAttributeTab.js, lib/ImportCategory.js, lib/ImportProduct.js, lib/utility.js, script/postman/pim-data-service.postman_collection.json, service/PimAttributeGroup.js
adding Attribute Groups to the import service
=> PIM-543 groups

index.js, lib/ImportAttributeLabel.js, lib/ImportProduct.js, script/postman/pim-data-service.postman_collection.json, service/PimAttributeLabel.js, service/PimAttributeValue.js
Adding the support to import attribute labels.
=> PIM-543 adding support for label import

lib/utility.js, script/postman/pim-data-service.postman_collection.json
Forgot to communicate this. Any type of data is sent as base64 from Apex now.
=> PIM-940: PIM | Import | Unable to import any data

lib/ImportAttributeGroup.js, lib/ImportAttributeLabel.js, lib/ImportAttributeTab.js, lib/ImportCategory.js, lib/ImportClass.js, lib/ImportProduct.js
All import related will extend from ImportClass to deal with body.
=> Refactor Import body

index.js, lib/ImportAssetLink.js, service/PimAsset.js, service/PimAttributeLabel.js
- New endpoint `/import/pim/assetlink`
- New Import class `ImportAssetLink`
- New service `PimAsset`
=> PIM-939: PIM | Import | New import type for digital asset relationships

lib/ImportAttributeLabel.js, script/postman/pim-data-service.postman_collection.json
I added support for adding label types and if there are picklist values to add them.
One issue I can't get the picklist values to save. Is there something I am missing about label picklist values?
=> PIM-543 adding support for attribute types

lib/ImportProduct.js, service/PimProduct.js
Using `queryExtend` so no more limit on the call out
=> PIM-985: PIM | Import | Break through current import limitations (Part 1)

lib/ImportProduct.js
Replace non existent method `addSingleLog` to fix error handling
=> [Hotfix] Replace problematic `addSingleLog`

lib/ImportProduct.js, service/History.js
Supporting PR for the main one on PIM for import history
=> PIM-1006: History logging for Product/Variant Imports

script/postman/pim-data-service.postman_collection.json
just updating the Postman stuff.
=> updating the postman config

lib/ImportCommerceProduct.js, obj/ImportConfiguration.js, service/CommerceParentVariant.js, test/CommerceProduct.test.js
Hey team is this pretty? no. Does it work? kinda. Will I update it? yes.
The goal of this PR is to get something in the hands of pre-sales people so they can start showing this to prospects, customers, and salesforce sales people.
I was pushed in the direction of a prototype/demo code instead of building a product. My guess is I will continue to build out feature and make this way more better, but for now I just need this in staging so I can call it from an SFDC org.
=> PIM-1205 | prototype

lib/ImportCommerceProduct.js, service/CommerceParentVariant.js
removing title as it needs to support overwrites.
=> PIM-1214 | removing title and adding it to the mapping

lib/ImportAssetLink.js, lib/ImportAssetMetadata.js, lib/ImportAttributeLabel.js, lib/ImportProduct.js, lib/utility.js, service/PimAttributeLabel.js, service/PimAttributeValue.js
First PR, mainly updating metadata (category, existing attribute values, and creating new attribute values) of existing digital assets. 
As mentioned previously, supporting the creation of digital assets from import will be quite a big undertaking, as we have to support using a customer's CDN as well. This will require changes to retrieval of assets via the creation of the view link and also the retrieval of the asset thumbnail.
https://github.com/PropelPLM/pim-data-service/assets/77341283/aba73a99-56a6-4d0b-aed7-23830901aaa2
=> PIM-688: PIM | Import | Digital Asset Metadata

lib/ImportAttributeLabel.js, script/postman/pim-data-service.postman_collection.json
Updated a few things to make Attribute Label import work.
=> PIM-994 | fixed the import

legacy/ExportPIM.js, legacy/utils.js, lib/ImportAssetMetadata.js, package-lock.json, package.json, test/utils.test.js
https://github.com/PropelPLM/pim-data-service/assets/77341283/f82976cc-5a2e-4f65-a869-6a2c226c2b51
- store full DA url in import
- change DA metadata import header 
- remove unused utility methods (e.g. `prependCDNToViewLink`, calls to get base url from PIM Constants)
- retrieve, zip, and post DA to chatter during export
- export full CDN url
=> PIM-1326: PIM | DA | Store full URL

lib/ImportProduct.js
the reason this was happening is import sends the data to the regular 255 value field but the trigger logic in Apex is to look at Value_Long__c first and then move it to Value__c if it's under 255 Characters. Just followed suit.
=> PIM-1344 | sending the value to value long

lib/ImportCommerceProduct.js, script/postman/pim-data-service.postman_collection.json, service/CommerceParentVariant.js
I am now passing a new object called `options` and in options I am using the Commerce Cloud reference for the Variant Set or Attribute Set that is mapped to this category and product. Then making sure I am getting the matching PIM variant Values.
=> PIM-1351 | setting variants to be dynamic

service/CommerceParentVariant.js
one more little change to support the custom fields.
=> PIM-1376 | got to add the __c

service/CommerceParentVariant.js, test/CommerceParentVariant.test.js, test_data/PropelHelperMock.js
forgot to test without a namespace.
=> PIM-1412 | fixing namespaceplus

service/CommerceParentVariant.js, test/CommerceParentVariant.test.js, test_data/PropelHelperMock.js
=> Pim 1412 fix

lib/ImportAttributeLabel.js
this change uses the new line instead of the return so salesforce is more happy
=> PIM-994 | switching from \r to \n

service/CommerceParentVariant.js
forgot about this one till I looked at the logs.
=> PIM-1419 | removing the console log of the helper

lib/ImportAssetMetadata.js
=> PIM-1276-2: PIM | Import | Support digital asset creation with other CDN urls

legacy/utils.js
- pass in Map of attribute primary key => attribute label to aspose
Corresponding PR in propel-document-java: https://github.com/PropelPLM/propel-document-java/pull/52
=> PIM-972-3: PIM | Template Export | Make template export support both primary_key and label for attributes

legacy/PimStructure.js
So as it turns out the open PR was for the original change. Turns out it never was merged weird.
=> PIM-1359 | forgot one place that needs the logic

legacy/ExportPIM.js, lib/ImportAttributeLabel.js
- cleanup
- add support for different cases for Attribute Label type field value
=> PIM-1449-2: PIM | AMS | Topic 2 | C | Numeric Import Attribute, Data & Export

lib/ImportAssetLink.js, lib/ImportAssetMetadata.js, lib/ImportAttributeGroup.js, lib/ImportAttributeLabel.js, lib/ImportAttributeTab.js, lib/ImportCategory.js, lib/ImportClass.js, lib/ImportCommerceProduct.js, lib/ImportProduct.js, service/PimAttributeValue.js, service/PimProductDeep.js
- Basically wrapping all `await` calls in the `start()` methods of each import class in a `try-catch` block.
- Add defensive checks `?.` for certain chained accessors.
- Add a check for the `attribute.Attribute_Label__r.Name`. If `undefined`, throw error.
=> PIM-1592 | PIM | Heroku | Prevent Server from crashing

service/PimAttributeValue.js
Missing namespace when get field
=> PIM-1634: PIM | Digital Assets | Update DA metadata

index.js, legacy/PimStructure.js
- The variants with the same created date can cause the query in random order
- Fix order by Order__c
=> PIM-1701: PIM | Export lowest level failed

legacy/ExportPIM.js, legacy/utils.js
Made hostname a variable 
PIM PR: https://github.com/PropelPLM/PIM/pull/1513
=> PIM-1700: PIM | Export should point to JAVA production

lib/ImportAttributeLabel.js
https://github.com/user-attachments/assets/6ffbf8f9-b98d-4833-ad4b-b3795c2854bd
=> PIM-1764: PIM | Product Completeness | Ability to Import Is Required field

legacy/PimRecordListHelper.js, legacy/PimRecordService.js
- Updated `Product_Category_Link__c` which has been renamed to `Alternate_Category_Link__c`
- Fix typo `Value__Long__c`
- Fixed bug caused by products with no primary category
=> PIM-1917: PIM | Export | Error with category link

legacy/PimRecordListHelper.js, legacy/PimRecordService.js, legacy/utils.js
- Add `Completeness Score` column to the exported file (for both `csv` and `xlsx`)
- Display logic is same as the UI:
- If `completeness score >= 0`, it will display that value (`0` or more),
- if `completeness score < 0 || null || undefined`, it will display `--`.
**csv:**
**xlsx:**
=> PIM-1968 | PIM | API | Export All API not showing completeness score
