PropelPLM/pim-data-service

index.js, legacy/ExportPIM.js, legacy/PimProductListHelper.js, legacy/PimStructure.js
Fix the bug that prevented template export from working.
https://user-images.githubusercontent.com/77341283/198339000-ad620734-f7ee-44c2-80ca-ba0c26a0e872.mov
Apart from all the automatic style changes from Prettier, the main changes for the bug fix are at 
- PimProductListHelper.js line 123, 124
- PimStructure.js line 321, 322
The root cause of the problem is the discrepancy between 3 different types of double quotes, which are now fully accounted for in the regex in lines 124 and 322 mentioned above. Previously this was not an issue as perhaps Salesforce ContentVersion converted all 3 types of double quotes (ASCII Codes 34, 8220, and 8221) to ASCII Code 34 (just a guess).
=> PIM-417: PIM | Export Template | Add the ability to load multiple templates

.gitignore, .prettierrc, legacy/ExportPIM.js, legacy/PimProductListHelper.js, legacy/PimProductService.js, legacy/PimStructure.js, legacy/utils.js
New feature:
- When Attribute Labels that are typed Digital Assets are in the export columns, if there are Attribute Values i.e. S3 assets, send a request to the Cloud File Storage Heroku app for it to download, zip and post the assets to chatter.
Fix:
- When top-level products are exported with NO variants, their Attribute Values are missing in the export. This PR makes sure they are added in the eventual XLSX.
Couple of refactorings as well to try to make the code a little more friendly.
Supported by https://github.com/PropelPLM/CloudFileStorage/pull/24 and https://github.com/PropelPLM/PIM/pull/567
=> PIM-442: Digital Asset List page | Binary Export

legacy/PimStructure.js
When doing the binary export, I mistook the calls to `addExportColumns` be identical. Changed the parameters back to the original for PDP export.
=> PIM-613: Export | PDP page export error

data/product_data.csv, lib/ImportProduct.js, local/testImportProduct.js, service/PimProduct.js
turns out I was relying on the file to provide the data but turns out that the import file will not have the variant data. This update uses the variant data that is in salesforce. So if it's created by the category or if they wan to add the variants with this file they can.
=> PIM-654 bug with import

legacy/PimStructure.js
Fixed bug from refactoring export preventing exporting when there are overwritten variant values.
=> PIM-294: PIM | Export | New export format XLSX

legacy/PimStructure.js
- Added null check for variant values (previously assumed users wont select filling in inherited data or exporting all variants if there weren't variant values in the product)
- Fixed typo
=> PIM-714: PIM | Export | Export failing in PDP for products without variant values and when filling in inherited data

legacy/PimStructure.js
- Added validation check to differentiate between current record exports for base product vs variant values
Current record export working for product
Current record export working for variant value
=> PIM-886: PIM | Export | Current Record Export on Base Product is Returning Empty File

legacy/ExportPIM.js
- Remove single quotes from regex so they are not converted to double quotes to allow them to be preserved in the exported xlsx
https://github.com/PropelPLM/propel-document-java/pull/28
=> PIM-884: PIM | Export is using commas in values to delimit columns

legacy/ExportPIM.js, legacy/utils.js
- Fixed the clean string method
- Abstracted string cleaning to utils
CSV
XLSX
=> PIM-895: PIM | Export | Export having issues when first character of attribute value is a double quote

data/category_data.csv, lib/ImportCategory.js, local/testImportCategory.js, package-lock.json, package.json
Here is my first attempt to convert over to a connected app, with JWT flow.
Steps:
1. if you are not using the `propel-sfdc-connect` npm package, please do so. version 1.3.1
2. The logical flow is first pass the connected app id (clientId) and username into the `jwtSession` function. along with `isTest` and the `privateKey`. The `privateKey` is an ENV VAR and is already deployed on staging and prod.
3. the `jwtSession` function will take these options and return back a session id.
4. Use that session id, and host url to create a connect object.
If you do not want to convert to `propel-sfdc-connect` then you can still use `propel-sfdc-connect` just for `jwtSession` and then use the session id as you would currently.
=> PIM-897 converting category over

legacy/ExportPIM.js, lib/utility.js, package-lock.json, script/postman/pim-data-service.postman_collection.json
I've moved the client Id to Heroku as a env var but wanted to leave the ability to pass the client id into the service is for some reason you needed to do that. Maybe we don't need this, thoughts?
I put the check for clientId back because the code that is being used for our security review still expects the clientId to be passed to Heroku. But when the security review is done then we can remove this check.
=> PIM-926 adding a check for the client Id

legacy/PimStructure.js
Remove base product when doing SKU export for both inherited and non inherited export, since it should not show base product just like current variant export.
=> PIM-910: PIM | Export | Lowest Variants of product export includes main product

legacy/ExportPIM.js, legacy/PimRecordListHelper.js, legacy/PimStructure.js, test/PimStructure.test.js
https://github.com/PropelPLM/pim-data-service/assets/77341283/1c676d8f-82ba-4da4-8c7e-d811af823147
*Note a slight change after recording - removed the <Invalid Attribute> tag to standardize with xlsx
- added support for multiple header rows
- some refactoring to reduce time complexity
- fixed tests (`templateHeaders` is a list of lists in order to support multiple headers so length of `templateHeaders` in test file is 1 instead of 2)
- added edge case support for invalid attributes
=> PIM-961: PIM | Export | Template Export Should Dynamically Establish Data Row Containing Attributes

lib/ImportProduct.js, service/PimVariantValue.js
- prevents Variant_Value duplicate query
- change insert to `insertSlice` with size 500 to break limits. (insert have 10k row limits)
=> PIM-985: PIM | Import | Break through current import limitations (Part 2)

legacy/PimStructure.js, legacy/utils.js
Added inheritance for digital asset export by keeping track of digital assets after parsing in a `Map<productId/variantValueId, Map<attributeLabelId, digitalAssetObject>>`
Recording for demo would be too exhaustive so here's a list of the scenarios I tested, covering all export types and both digital asset and non-digital asset fields
=> PIM-917-2: PIM | Export | Current Record export type should only export that records digital asset

legacy/ExportPIM.js, legacy/PimStructure.js, legacy/utils.js
https://github.com/PropelPLM/pim-data-service/assets/77341283/78113156-3f10-4765-854b-bc006cff30ba
- return xlsx template without modification if no attribute flags are found
Link to PR for propel-document-java: https://github.com/PropelPLM/propel-document-java/pull/40
=> PIM-1078: PIM | Export | Template export without attribute flag should simply return template

lib/ImportCategory.js
I am not sure what I was thinking that the one at a time insert would work at high volumes. But here is the fix.
I insert all the categories at once, and parent them to the root. Then go though and update the real parent.
=> PIM-1292 | moving away from brute force

legacy/ForceService.js, legacy/utils.js, lib/ImportAssetMetadata.js, lib/ImportClass.js, test/utils.test.js
- get Digital Asset size and mime type from URL provided at import
- get CDN information from PIM
- store CDN identifier as field value at `Digital_Asset__c.Content_Location__c`
- extend product export to support multiple CDNs when constructing the complete CDN URL from the truncated `View_Link__c`
- update the newly created `Digital_Asset__c` with attribute values for attributes specified in import
https://github.com/PropelPLM/pim-data-service/assets/77341283/29a3575e-4b9c-4050-b307-4695047aa2c4
PIM PR: https://github.com/PropelPLM/PIM/pull/1271
=> PIM-1276: PIM | Import | Support digital asset creation with other CDN urls

legacy/PimRecordListHelper.js, legacy/PimStructure.js, legacy/utils.js
https://github.com/PropelPLM/pim-data-service/assets/77341283/7a33d452-2667-4b3b-9784-ed638ae18544
- lowest variant export aka SKU export will now export SKUs of the selected records even if some of the SKUs were among the selected records
- this is regardless if the selected record is a product, non SKU variant value, or SKU variant value
=> PIM-1328: PIM | Export | PLP export with parent only selected and Export lowest option selected will not export lowest variants

legacy/PimRecordListHelper.js, legacy/PimStructure.js
- add `Primary_Key__c` field to the query for `Attribute_Label__c`
- if template field matches either `Primary_Key__c` or `Label__c` field of `Attribute_Label__c`, create an export column corresponding to that `Attribute_Label__c`
https://github.com/PropelPLM/pim-data-service/assets/77341283/d6c61725-bdb0-4176-a58c-dd0abd4bf9cd
=> PIM-972: PIM | Template Export | Make template export support both primary_key and label for attributes

service/CommerceParentVariant.js
I had the order of variant values wrong this PR is to fix that so the Values line up with the column headings.
=> PIM-1392 | fixing the order of variant values issue

lib/ImportCategory.js
Looks like this method in PIM, `beforeInsertMaxNodeDepth` causes the SOQL limits to get out of control really fast. In about 166 category inserts. So this change slices up the batches into sets of 100 so that method stays low. 
We should think about removing it anyway not sure why we care about Categories having more than 12 kids.
=> PIM-1381 | slice it up bruh

legacy/PimRecordListHelper.js, legacy/PimRecordService.js
Added ternary operator to only append first record when it's digital asset export (preventing duplicate 1st record when product and variants are populated afterwards)
=> PIM-1456: PIM | Export | PLP export is duplicating first record

legacy/PimRecordListHelper.js
- Fixed a typo (lines 487 and 525) that just check if `([helper.namespace('Value_Long__c')])` evaluates to true. 
- Line 435 is technically correct but changing it for consistency and to be more readable
=> PIM-1473: PIM | Export | PLP Export Does Not Show Inherited Values

legacy/PimStructure.js
I compared the two PIM Logs from QA to UAT and saw the tell-tell sign of namespace. The genius that implemented Logger in PIM will always be valued. Thank goodness he was smart enough to create a tool that made it easy to fine all of his own mistakes. Looks like this will be my last PR for the Propel eng team. Seems fitting I am fixing a bug I caused, but I am proud of what the PIM team created, and I am proud I was apart of it. I feel like there is so much more todo and with a sad heart I will not be able to finish what I started.
=> PIM-1524 | forgot one place for namespace

index.js, legacy/ExportPIM.js
Related PR in PIM: https://github.com/PropelPLM/PIM/pull/1712
- Shift creating of filenames into parent method so that we can return it. Else if it were to be done in the `LegacyExportPIM()` method, it would not run finish in time for the filenames to be returned.
- Export now returns:
```
{
exportFilename: filename,
daZipFilename
}
```
- Do check for `includeRecordAsset`. If true, the DA zip file will be sent to Chatter, else it won't.
- Add `exportFormat` into filename.
**NOTE:** I've tested exporting via UI and it still works as expected. No change in behavior. DA zip files are still posted to Chatter.
=> PIM-1937 | PIM | API | New Export API for entire database

lib/ImportAssetMetadata.js
- if File Name value exceeds 255 characters, row is not imported/updated
- if File Name is empty and Digital Asset Record value exceeds 80 characters, PIM_Digital_Asset_Name__c will be populated with the Digital Asset Record value, and then Digital Asset Record value will be truncated to 80 characters before storing in the Name field
- Fixed bug where row update is skipped if no value for category id
PIM PR: https://github.com/PropelPLM/PIM/pull/1751
=> PIM-1414: PIM | DA | Uploading a file name greater > 80 Charcters
